# Generated by Django 4.2.9 on 2025-09-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backtester", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backtestresult",
            name="max_drawdown",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
