# Generated by Django 4.2.9 on 2025-09-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtester', '0002_alter_backtestresult_max_drawdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestconfig',
            name='backtester_type',
            field=models.CharField(default='spot_simple', max_length=20),
        ),
    ]
