# Generated by Django 4.2.9 on 2025-09-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="strategy_type",
            field=models.CharField(
                choices=[("moving_average_crossover", "Moving Average Crossover")],
                max_length=50,
            ),
        ),
    ]
