# Generated by Django 4.2.9 on 2025-09-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_alter_strategy_strategy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='strategy_type',
            field=models.CharField(choices=[('moving_average_crossover', 'Moving Average Crossover'), ('moving_average_crossover_rsi', 'Moving Average Crossover + RSI')], max_length=50),
        ),
    ]
